### ISSUE TITLE
要素名について

### ISSUE THREAD

**Issue by naoyanzu** [DEE-BRI/arcclimate#11]
J列からQ列に格納されているデータに関して、格納されているデータの要素名や内容について教えていただけますでしょうか。
![2022-07-11 (3)](https://user-images.githubusercontent.com/107521646/178207497-d8064867-5728-4610-aac9-16839e4e9c00.png)

**Comment by iizumi-genki** [comment]
ありがとうございます。

J列　RH：相対湿度[％]
K列　Pw：水蒸気分圧 [hpa]
L列　DT：露点温度[℃]
M列　DN_est：直達日射（推計値・直散分離の結果）[MJ/m2]
N列　SH_est：直達日射（推計値・直散分離の結果）[MJ/m2]
O列　DN_msm：直達日射（MSM値・直散分離の結果）[MJ/m2]
P列　SH_msm：直達日射（MSM値・直散分離の結果）[MJ/m2]
Q列　NR：夜間放射量[MJ/m2]
です。

なお、M～P列は直散分離の結果で、
M,N列は雲量等から推計した日射量の結果
O,P列はMSMが公開している日射量（2017年12月以降のみ）の結果
で、どちらかを使用することになります。

後日、ReadMeにも追加しておきます。

**Comment by yuizi** [comment]
拡張アメダスの[直散分離の資料](https://www.metds.co.jp/?smd_process_download=1&download_id=639)から、M～P列の略称DN,SHは、

M列　DN_est：法線面直達日射（推計値・直散分離の結果）[MJ/m2]
N列　SH_est：水平面天空日射（推計値・直散分離の結果）[MJ/m2]
O列　DN_msm：法線面直達日射（MSM値・直散分離の結果）[MJ/m2]
P列　SH_msm：水平面天空日射（MSM値・直散分離の結果）[MJ/m2]

ではないでしょうか？ご確認いただけると幸いです。

**Comment by iizumi-genki** [comment]
失礼いたしました。
入力の誤りで、ご指摘の通りです。

M列　DN_est：法線面直達日射（推計値・直散分離の結果）[MJ/m2]
N列　SH_est：水平面天空日射（推計値・直散分離の結果）[MJ/m2]
O列　DN_msm：法線面直達日射（MSM値・直散分離の結果）[MJ/m2]
P列　SH_msm：水平面天空日射（MSM値・直散分離の結果）[MJ/m2]

ご指摘ありがとうございました。

**Comment by naoyanzu** [comment]
確認いたしました。
お二方とも、お忙しい中質問に答えていただきありがとうございました。
