### ISSUE TITLE
1年分のEPWを出力するには？

### ISSUE THREAD

**Issue by yuizi** [DEE-BRI/arcclimate#25]
EPW形式で1年分（単年度分）を出力したいのですが、うまくできません。

--start/end_yearへ同じ年を指定した場合、2010/12/31の19時～24時のみ出力されます。

`arcclimate 35.69 139.76 -o Tokyo2010-2010.epw -f EPW --start_year 2010 --end_year 2010
`

開始年、翌年の指定かと--start/end_yearをそれぞれ2010，2011として出力した場合。

`arcclimate 35.69 139.76 -o Tokyo2010-2011.epw -f EPW --start_year 2010 --end_year 2011`

2010/12/31の19時から始まって、翌年2011/12/31 24時まで出力されます。

いずれにしても12/31の19時～24時分が含まれた形式になります。

1年分の出力方法をご教授ください。

上記で出力したファイルを添付いたします。

[Tokyo2010-2010.zip](https://github.com/DEE-BRI/arcclimate/files/14075243/Tokyo2010-2010.zip)
[Tokyo2010-2011.zip](https://github.com/DEE-BRI/arcclimate/files/14075244/Tokyo2010-2011.zip)

## 追記
2020ではうまく出力できました。
`arcclimate 35.69 139.76 -o Tokyo2020.epw -f EPW --start_year 2020 --end_year 2020`

## 追記2
気象データの範囲（2011～2020年）の記述を見落としていました。

> The data can be generated for a 10-year period from January 1, 2011 to December 31, 2020 (Japan Standard Time). 

もそも範囲外の年を--start_year へ指定していました。大変失礼いたしました。

**Comment by udawtr** [comment]
@yuizi 
気づくのが遅れてすいませんでした。
すでに解決されたようで、良かったです。また何かお気づきの点がございましたら、ご指摘いただければと思います。
