### ISSUE TITLE
Windows環境で試すと、CSVの改行コードが2重（？）になっています

### ISSUE THREAD

**Issue by yuizi** [DEE-BRI/arcclimate#9]
Windows環境でQuick Startに従ってCSVを生成、Excelで開くと図のように1行飛ばしのデータになります。
改行コードを調べると**CRCRLF**が使われているため、おそらくExcelが改行が2重にあると解釈している状態だと思います。

ひとまずの対策としては、Excelで開く前にCSVをメモ帳アプリで開いて上書き保存するとWindows標準の改行コード（**CRLF**）に変換されます。
それほど深刻な問題でもないのですが、この点対応いただけるとWindows環境で使いやすくなると思います。
![kenken_EA csv](https://user-images.githubusercontent.com/4317135/177902233-67d1480c-fdf1-4cc6-bdf8-cde40cb6a531.png)

**Comment by iizumi-genki** [comment]
ありがとうございます。
CSV出力時の改行コードを修正をしました。

https://github.com/DEE-BRI/arcclimate/commit/36fe004ad21afd366f03d585d50db667706103ec

**Comment by yuizi** [comment]
改行コードの件、確認しました。修正ありがとうございました。
